- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma
    - name: enable puma
      systemd: name=puma enabled=yes
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
