- name: Provision App
  become: true
  tasks:
    - name: Install Ruby
      apt:
        name: ruby-full
        state: present

    - name: Install Bundler
      apt:
        name: ruby-bundler
        state: present

    - name: Install Build-essential
      apt:
        name: build-essential
        state: present
