- name: Provision App
  hosts: all
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
        allow_unauthenticated: true
        force: true

    - name: Install Ruby
      apt:
        name: ruby-full
        state: present

    - name: Install Bundler
      apt:
        name: ruby-bundler
        state: present

    - name: Install Build-essential
      apt:
        name: build-essential
        state: present
